### ISSUE TITLE
shoe received date

### ISSUE THREAD

**Issue by fjsousa** [gettruly/truly-api#2]
Qual o formato da "received_date" nos shoes?! tentei inserir a data com a instrução  Date() em javascript, mas o campo na base de dados ficou a '000-00-00 00:00'

**Comment by braincrash** [comment]
Basta usares NOW()
O formato deverá ficar assim: values in 'YYYY-MM-DD HH:MM:SS' format

Exemplo:
INSERT INTO shoe (donorsid,img,gender,size,type,received_date) 
VALUES ((SELECT id FROM donors WHERE email = 'jarbas@gmail.com'),'SDFSDassasDFASDF','F','33','sandalia',NOW())
