### ISSUE TITLE
create shoe with donor id

### ISSUE THREAD

**Issue by fjsousa** [gettruly/truly-api#3]

**Comment by tcorreiacontractor** [comment]
Tão lembraste te? :D

**Comment by braincrash** [comment]
Tão lembraste te? :D

**Comment by fjsousa** [comment]
tou me a orientar plos github issues agr e tive a fazer uma clean up

Flávio Sousa
datajournal.co.uk

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by braincrash** [comment]
Nice! :)
